name: Slack CI Notification
description: |
  Send CI status notification with thread support.
  - If thread_ts provided: reply in that thread (PR flow)
  - If thread_ts empty: send standalone message (push to main flow)

inputs:
  channel_id:
    required: true
    description: 'Slack channel ID to send notification to'
  status:
    required: true
    description: 'CI status: success, failed, cancelled'
  thread_ts:
    required: false
    description: 'Slack thread timestamp to reply to (from pr-checks output). If empty, sends standalone message.'
    default: ''
  slack_bot_token:
    required: true
    description: 'Slack bot token for authentication'

outputs:
  ts:
    description: 'Timestamp of sent message'
    value: ${{ steps.slack-standalone.outputs.ts || steps.slack-reply.outputs.ts }}

runs:
  using: composite
  steps:
    # If thread_ts is empty (push to main): send standalone CI status message
    - name: Send standalone CI status
      id: slack-standalone
      if: inputs.thread_ts == ''
      uses: slackapi/slack-github-action@v2.1.1
      with:
        method: chat.postMessage
        token: ${{ inputs.slack_bot_token }}
        payload: |
          {
            "channel": "${{ inputs.channel_id }}",
            "text": "CI for `${{ github.repository }}` - ${{ inputs.status }}",
            "attachments": [
              {
                "color": "${{ inputs.status == 'success' && 'good' || (inputs.status == 'failed' && 'danger' || 'warning') }}",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "`${{ inputs.status }}`"
                  },
                  {
                    "title": "Branch",
                    "short": true,
                    "value": "`${{ github.ref_name }}`"
                  },
                  {
                    "title": "Author",
                    "short": true,
                    "value": "${{ github.actor }}"
                  },
                  {
                    "title": "Build",
                    "short": true,
                    "value": "#${{ github.run_number }}"
                  },
                  {
                    "title": "Workflow",
                    "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Logs>"
                  }
                ]
              }
            ],
            "link_names": true,
            "mrkdwn": true
          }

    # If thread_ts is provided (PR flow): reply in thread only
    - name: Reply CI status in thread
      id: slack-reply
      if: inputs.thread_ts != ''
      uses: slackapi/slack-github-action@v2.1.1
      with:
        method: chat.postMessage
        token: ${{ inputs.slack_bot_token }}
        payload: |
          {
            "channel": "${{ inputs.channel_id }}",
            "text": "Status: `${{ inputs.status }}` | Build #${{ github.run_number }} [<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Logs>]",
            "thread_ts": "${{ inputs.thread_ts }}",
            "reply_broadcast": false,
            "link_names": true,
            "mrkdwn": true
          }
